function [] = player(); %This is the main player function that calls the other functions to create one game.%
disp('Welcome to Word Cookie!');
disp('Your job is to make as many words as you can with the given letters!');
disp('You have three minutes, and your time starts now!')

points = 0; %Player beings with points at 0 
used_words = []; %Creates an empty vector, used_words, to later populate with words the player has already inputted. This allows for matlab to recognize those words and not count them multiple times in the count_points function.%
letters = letter_draw(); %This calls the letter_draw function, which generates a random set of letters each run and sets that equal to the variable letters.%
iniTime = clock;
limit   = 180;  %Sets time limit to 180 seconds% 
while etime(clock, iniTime) < limit %A while loop is used to keep the game going until the clock/time runs out.%
    disp(letters); %Displays the letters generated by the letter_draw function.%
    word = input('Type word Here: ', "s"); %Code that allows the player to input their words%
    checking = word_checking(word); %This calls the word_checking function to check if the word is in the dictionary. Then the function assigns that to variable 'checking'.%
    if checking ==1 %If 'checking' is true (for example, if Matlab finds the inputted word in the dictionary).%
       [points, used_words] = count_points(word, points, letters, used_words); %Next, the count_points function is called to tally up the points for the word, and keep track of the previously inputted words.%
        pnts = ['Points: ',num2str(points)]; %This sets up an updated point value that can be displayed.%
        disp(pnts); %This actually displays the updated point value to the player.%
    else 
        disp('Not a word!'); %If Matlab does not find the inputted word in the dictionary, the phrase: 'Not a word' is displayed to the player.%
    end %Ends the if statement.%
end %Ends the while loop.%
disp('Time is up--thanks for playing!') %Displays a message after the player is done!%
great_job = imread('great_job.png'); %The command "imread" reads an image from a graphics file, in this case, "great_job.png".%
imshow(great_job) %The command "imshow" diplays the image%
end   %Ends the player function.%

